# Header http://blog.sprabbit.com/
menu:
#  Home: /#blog
  Archives: /archives
  Resume: /resume
# Site favicon
favicon: /favicon.png

# Site logo
# logo: /avatar.png

nav:
  -
    - categories # display a collapsible category list
    - tags       # display a collapsible tag list
    - archives   # display a collapsible archive list
  -
    -
      name: Homepage
      url: '/'
    -
      name: By Year
      url: /archives
  -
    -
      name: Github
      url: https://github.com/
    -
      name: RSS
      url: /atom.xml
