# Header http://blog.sprabbit.com/
menu:
#  Home: /#blog
  Archives: /archives
  Resume: /resume
# Site favicon
favicon: /favicon.png

# Site logo
# logo: /avatar.png
maxContentWidth: 1000px

nav:
  -
    - categories # display a collapsible category list
    - tags       # display a collapsible tag list
    - archives   # display a collapsible archive list
  -
    -
      name: 主页
      url: '/'
  -
    -
      name: Github
      url: https://github.com/

